project: 
   type: book
   output-dir: _book
   #resources: listings
   preview:
    browser: true
    watch-inputs: true
    timeout: 600
    
bibliography: references.bib
    
book:
  title: "Idaho Wheat Production Guide"
  description: "Resources for wheat production in Idaho and the surrounding region"
  reader-mode: true
  navbar:
    top:
      # - text: Home
      #   href: https://idahoagstats.github.io/wheat-production-guide-website/
      #   aria-label: Home
      # - text: About
      #   href: https://idahoagstats.github.io/wheat-production-guide-website/about.html
      #   aria-label: About the Project
        search: true
      
  page-footer:
    center: |
      [![](images/UI-Extension-H-4c.jpg){width=250px}](https://www.uidaho.edu/extension){target="_blank"}
    border: true
  cover-image: images/wheat-cover.png
  favicon: images/wheat-cover.png
  twitter-card: true
  image: images/wheat-cover.png
  open-graph: true
  #  site-url: # a site url

  
  chapters:
    - index.qmd
    - about.qmd
    - 1_quickfacts.qmd
    - 2_wheat_in_idaho_intro.qmd
    - 3_growth_and_development.qmd
    - 4_wheat_varieties_breeding.qmd
    - 5_variety_trial_database.qmd
    - 6_seed.qmd
    - 7_planting.qmd
    - 8_irrigation_management.qmd
    - 9_nutrient_management.qmd
    - 10_integrated_pest_management.qmd
    - 11_weed_control.qmd
    - 12_disease_disease_mgmt.qmd
    - 13_insect_pests_control.qmd
    - 14_nematodes.qmd
    - 15_drones_uav.qmd
    - 16_harvest_storage.qmd
    - 17_cropping_systems.qmd
    - 18_residue_management.qmd
    - 19_end_use_quality.qmd
    - 20_economics.qmd
    - 21_addl_resources.qmd
    
  

format:
  html:
    anchor-sections: true
#    embed-resources: true
    #page-layout: article
    linkcolor: "#008094"
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    fontsize: 1em
    smooth-scroll: true
    toc: true
    toc-depth: 5
    toc-title: On this page
    toc-location: right
    number-sections: true
    number-depth: 1
    link-external-icon: false
    link-external-newwindow: true
    comments: 
      hypothesis: 
        theme: clean
        
 # pdf: default
 #   page-navigation:
 #     back-to-top-navigation: true
 #     search:
 #       type: textbox
 #       collapse-after: 5
 #       copy-button: true
 # navbar:
#    right:
#      - href: index.qmd
#        text: Home
#      - about.qmd
editor: source

brand: _brand.yml

custom-callout:
  wpg:
    color: "#F1B300"
    icon: false
filters:
- custom-callout
