project: 
   type: website
   output-dir: _site
   resources: listings
   preview: 
     watch-inputs: false
     navigate: true

website:
  title: "Idaho Wheat Production Guide"
  description: "Resources for wheat production in Idaho and surrounding and region"
#  favicon: # path to a favicon
#  site-url: # a site url
  repo-url: "https://github.com/emilymg/wheat-production-guide-website"
  issue-url: "https://github.com/emilymg/wheat-production-guide-website/issues"
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search:
    type: textbox
    collapse-after: 5
    copy-button: true
  navbar:
    right:
      - text: "More"
        menu:
          - href: index.qmd
            text: Home
          - about.qmd

format:
  html:
    embed-resources: true
    page-layout: article
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    fontsize: 1em
    smooth-scroll: true
    toc: true
    toc-depth: 3
    toc-title: Contents
    toc-location: left
    #number-sections: true
    # number-depth: 1
    link-external-icon: true
    link-external-newwindow: true
  pdf: default

editor: source

