project: 
   type: website
   output-dir: _site
   resources: listings
   preview: 
     watch-inputs: false
     navigate: true

website:
  title: "Idaho Wheat Production Guide"
  description: "Resources for wheat production in Idaho and surrounding and region"
  #repo-url: "https://github.com/emilymg/wheat-production-guide-website"
  #issue-url: "https://github.com/emilymg/wheat-production-guide-website/issues"
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search:
    location: toc
    type: textbox
    collapse-after: 10
    copy-button: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
 #   embed-resources: true
    page-layout: article
    theme: flatly
    css: styles.css
    smooth-scroll: true
    toc: true
    toc-depth: 4
    highlight-style: arrow
  pdf: default

editor: source

