project: 
   type: book
   output-dir: _book
   #resources: listings
   preview:
    browser: true
    watch-inputs: false
    navigate: true
    timeout: 600
    
book:
  title: "Idaho Wheat Production Guide"
  reader-mode: true
  
  page-footer:
    left: |
      The Idaho Wheat Production Guide is produced by the University of Idaho with support from the Idaho Wheat Commission. Contributors include Idaho and regional researchers.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/wheat-cover.png
  favicon: images/wheat-cover.png
  #  site-url: # a site url
#  repo-url: "https://github.com/IdahoAgStats/wheat-production-guide-website"
#  issue-url: "https://github.com/IdahoAgStats/wheat-production-guide-website/issues"
  
  
  chapters:
    - index.qmd
    - about.qmd
    - 1_quickfacts.qmd
    - 2_wheat_in_idaho_intro.qmd
    - 3_growth_and_development.qmd
    - 4_wheat_varieties_breeding.qmd
    - 5_variety_trial_database.qmd
    - 6_seed.qmd
    - 7_planting.qmd
    - 8_irrigation_management.qmd
    - 9_nutrient_management.qmd
    - 10_weed_control.qmd
    - 11_disease_disease_mgmt.qmd
    - 12_insect_pests_control.qmd
    - 13_drones_uav.qmd
    - 14_harvest_storage.qmd
    - 15_cropping_systems.qmd
    - 16_residue_management.qmd
    - 17_end_use_quality.qmd
    - 18_economics.qmd
    - 19_addl_resources.qmd
    
  description: "Resources for wheat production in Idaho and surrounding and region"


format:
  html:
#    embed-resources: true
    #page-layout: article
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    fontsize: 1em
    smooth-scroll: true
    toc: true
    toc-depth: 3
    toc-title: On this page
    toc-location: right
    number-sections: true
    number-depth: 3
    link-external-icon: false
    link-external-newwindow: true
 # pdf: default

#  page-navigation:
#  back-to-top-navigation: true
#  search:
#    type: textbox
#    collapse-after: 5
#    copy-button: true
#  navbar:
#    right:
#      - href: index.qmd
#        text: Home
#      - about.qmd
editor: source

